In [38]:
import matplotlib.pyplot as plt
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

pd.set_option("display.max_columns",100, 'display.max_rows',100)

In [2]:
shows_played = 0
num_venues = 0
avg_revenue = 0 
total_revenue = 0 
avg_ticket_price = 0 
tickets_sold = 0

In [3]:
d = np.array([[shows_played,num_venues,avg_revenue,total_revenue,avg_ticket_price,tickets_sold]])

artist_df = pd.DataFrame(   data = d, 
                            columns = ['shows_played','num_venues','avg_revenue','total_revenue',
                                        'avg_ticket_price','tickets_sold'])

In [49]:
#parameters for later use

venue_name = np.array(['Ball Arena','Summit Music Hall','Marquis Theater','Dazzle',
                                    "Ophelia's Electric Soapbox","Herb's","Black Buzzard","Paramont Theatre",
                                    "Roxy Theatre","Cervantes & The Other Side","Mission Ballroom","Larimer Lounge",
                                    "Globe Hall","Ogden Theatre","Lost Lake","Walnut Room","Globe Hall","Your Mom's House",
                                    "Herman's Hideway","Broadway Roxy"])

show_col = ['show_id','name', 'age', 'gender', 'tickets_bought']

In [28]:
#artist database

shows_played = 0
num_venues = 0
avg_revenue = 0 
total_revenue = 0 
avg_ticket_price = 0 
tickets_sold = 0

artist = np.array([[shows_played,num_venues,avg_revenue,total_revenue,avg_ticket_price,tickets_sold]])

artist_df = pd.DataFrame(   data = artist, 
                            columns = ['shows_played','num_venues','avg_revenue','total_revenue',
                                        'avg_ticket_price','tickets_sold'])

In [54]:
#generating buyer profile

def buyer_show(show_num):
    ''' 
        creates buyer profile to be added to panda dataframe
        show_num = show number
    '''
    show_id = show_num
    name = np.random.choice(['Kirsty Millington', 'Donald McSherry', 'Charlotte Worth', 'Andre Botelho', 
                            'Keanu Reeves', 'John Travolta', 'Danzel Washington', 'Marlon Brandon', 
                            'Reese Witherspoon', 'Maryl Strip', 'Mari Nishida', 'Dustin Hoffman', 
                            'Bruce Wayne','Tony Stark', 'Peter Parker', 'Scarlett Johanssen', 
                            'Cristina Abdalla','Ronda Rousey','Joel Miller', 'Kalum Rooney',
                            'Luna Timms', 'Margaux Wolfe','Nazifa Jimenez','Wasim Gaines','Oliver Case',
                            'Aizah North','Harry Goodwin','Kerys Peralta', 'Bear Williamson',
                            'Dani Cunningham', 'Jayda Hutchings','Kobie Sears','Julie Wallace',
                            'Garry Mclellan','Virgil Gibbs','Alan Marquez','Fraser Barron'], replace=False)

    age = np.random.randint(18, 50)
    gender = np.random.choice(['M','F','NB','T'])
    num_bought = np.random.randint(1,5)
    ticket_bought = np.random.randint(1,5)


    buyer_profile = [show_num, name,age,gender, ticket_bought]

    return buyer_profile

In [55]:
#generating the dataframe per show and adding constant features per show

def generate_df(num, show_num, v):
    '''
    num (int) = total attendees sold
    v (str) = venue name
    '''
    show_data = []
    
    for i in range(num):
        show_data.append(buyer_show(show_num))

    show_df = pd.DataFrame(data = show_data, columns = show_col)

    show_df['ticket_price']=np.random.choice(np.array([5,10,15,20]))
    show_df['total_revenue']= show_df['ticket_price']*show_df['ticket_bought']
    show_df['venue_name'] = v

    return show_df

In [56]:
#concatenating the data for different shows

def concat_shows(original_df, to_concat_df):
    show_df = pd.concat((original_df, to_concat_df), axis=0)
    show_df.reset_index(inplace=True, drop=True)
    return show_df

In [57]:
show1 = generate_df(np.random.randint(1, 31),1, np.random.choice(venue_name))
show2 = generate_df(np.random.randint(1, 31),2, np.random.choice(venue_name))
show3 = generate_df(np.random.randint(1, 31),3, np.random.choice(venue_name))
show4 = generate_df(np.random.randint(1, 31),4, np.random.choice(venue_name))
show5 = generate_df(np.random.randint(1, 31),5, np.random.choice(venue_name))

In [58]:
show_df = concat_shows(show1, show2)
show_df = concat_shows(show_df, show3)
show_df = concat_shows(show_df, show4)
show_df = concat_shows(show_df, show5)

In [59]:
show_df['venue_name'].unique()

array(['Ogden Theatre', 'Ball Arena', 'Broadway Roxy', 'Larimer Lounge',
       "Ophelia's Electric Soapbox"], dtype=object)

In [60]:
show_df

,show_id,name,age,gender,ticket_bought,ticket_price,total_revenue,venue_name
0,1,Kobie Sears,39,T,2,15,30,Ogden Theatre
1,1,Kerys Peralta,45,T,2,15,30,Ogden Theatre
2,2,Julie Wallace,40,M,2,20,40,Ball Arena
3,2,Oliver Case,28,F,2,20,40,Ball Arena
4,2,Dustin Hoffman,30,M,2,20,40,Ball Arena
5,2,Kalum Rooney,21,F,4,20,80,Ball Arena
6,2,Scarlett Johanssen,25,F,2,20,40,Ball Arena
7,2,Bruce Wayne,49,F,3,20,60,Ball Arena
8,2,John Travolta,25,M,2,20,40,Ball Arena
9,2,Reese Witherspoon,40,F,2,20,40,Ball Arena
10,2,Virgil Gibbs,23,T,1,20,20,Ball Arena
11,2,Dani Cunningham,21,NB,2,20,40,Ball Arena
12,2,Keanu Reeves,46,F,3,20,60,Ball Arena
13,2,Peter Parker,21,T,3,20,60,Ball Arena
14,2,Bear Williamson,27,NB,2,20,40,Ball Arena
15,2,Peter Parker,20,NB,1,20,20,Ball Arena
16,2,Dustin Hoffman,38,T,3,20,60,Ball Arena
17,2,Bear Williamson,42,M,3,20,60,Ball Arena
18,2,Alan Marquez,19,F,4,20,80,Ball Arena
19,2,Fraser Barron,42,F,1,20,20,Ball Arena
20,2,Virgil Gibbs,40,F,2,20,40,Ball Arena
21,3,Nazifa Jimenez,47,T,4,20,80,Broadway Roxy
22,3,Virgil Gibbs,36,T,4,20,80,Broadway Roxy
23,3,Virgil Gibbs,41,M,3,20,60,Broadway Roxy
24,3,Virgil Gibbs,34,F,3,20,60,Broadway Roxy
25,3,Kirsty Millington,32,M,1,20,20,Broadway Roxy
26,3,Margaux Wolfe,36,T,1,20,20,Broadway Roxy
27,3,Charlotte Worth,23,F,3,20,60,Broadway Roxy
28,3,Tony Stark,22,NB,1,20,20,Broadway Roxy
29,3,Danzel Washington,48,M,2,20,40,Broadway Roxy
30,3,Maryl Strip,18,F,4,20,80,Broadway Roxy
31,3,Andre Botelho,28,NB,3,20,60,Broadway Roxy
32,3,Oliver Case,34,M,4,20,80,Broadway Roxy
33,3,Mari Nishida,48,F,1,20,20,Broadway Roxy
34,3,Danzel Washington,31,F,2,20,40,Broadway Roxy
35,3,Julie Wallace,23,M,1,20,20,Broadway Roxy
36,3,Ronda Rousey,18,NB,2,20,40,Broadway Roxy
37,4,Alan Marquez,18,F,1,10,10,Larimer Lounge
38,4,Donald McSherry,22,NB,3,10,30,Larimer Lounge
39,4,Kobie Sears,39,NB,3,10,30,Larimer Lounge
40,4,Virgil Gibbs,36,F,2,10,20,Larimer Lounge
41,4,Fraser Barron,33,F,1,10,10,Larimer Lounge
42,4,Dustin Hoffman,27,T,1,10,10,Larimer Lounge
43,4,Bruce Wayne,22,NB,4,10,40,Larimer Lounge
44,4,Andre Botelho,45,F,4,10,40,Larimer Lounge
45,4,Keanu Reeves,22,F,2,10,20,Larimer Lounge
46,4,Danzel Washington,23,T,1,10,10,Larimer Lounge
47,4,Kirsty Millington,37,T,4,10,40,Larimer Lounge
48,4,Harry Goodwin,46,F,3,10,30,Larimer Lounge
49,4,Reese Witherspoon,19,T,1,10,10,Larimer Lounge
50,4,Danzel Washington,29,NB,1,10,10,Larimer Lounge
51,4,Ronda Rousey,37,F,4,10,40,Larimer Lounge
52,4,Andre Botelho,42,NB,1,10,10,Larimer Lounge
53,4,Fraser Barron,31,T,1,10,10,Larimer Lounge
54,4,Joel Miller,43,F,2,10,20,Larimer Lounge
55,4,Alan Marquez,28,NB,4,10,40,Larimer Lounge
56,4,Margaux Wolfe,29,NB,1,10,10,Larimer Lounge
57,4,Peter Parker,39,M,2,10,20,Larimer Lounge
58,4,Charlotte Worth,44,NB,4,10,40,Larimer Lounge
59,4,Dustin Hoffman,48,NB,2,10,20,Larimer Lounge
60,4,Marlon Brandon,40,F,3,10,30,Larimer Lounge
61,4,Cristina Abdalla,42,NB,3,10,30,Larimer Lounge
62,4,Kerys Peralta,36,NB,3,10,30,Larimer Lounge
63,4,Aizah North,35,F,3,10,30,Larimer Lounge
64,4,Mari Nishida,40,T,4,10,40,Larimer Lounge
65,4,Margaux Wolfe,42,T,1,10,10,Larimer Lounge
66,4,Luna Timms,21,NB,3,10,30,Larimer Lounge
67,5,Alan Marquez,31,T,4,10,40,Ophelia's Electric Soapbox
68,5,Joel Miller,44,F,4,10,40,Ophelia's Electric Soapbox
69,5,Julie Wallace,25,F,3,10,30,Ophelia's Electric Soapbox
70,5,Andre Botelho,33,T,2,10,20,Ophelia's Electric Soapbox
71,5,John Travolta,31,T,4,10,40,Ophelia's Electric Soapbox
72,5,Cristina Abdalla,36,NB,3,10,30,Ophelia's Electric Soapbox
73,5,Reese Witherspoon,45,F,4,10,40,Ophelia's Electric Soapbox
74,5,Kalum Rooney,49,NB,3,10,30,Ophelia's Electric Soapbox
75,5,Kalum Rooney,20,T,3,10,30,Ophelia's Electric Soapbox
76,5,Charlotte Worth,27,T,1,10,10,Ophelia's Electric Soapbox
77,5,Julie Wallace,39,F,1,10,10,Ophelia's Electric Soapbox
78,5,Alan Marquez,27,NB,2,10,20,Ophelia's Electric Soapbox